name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20'

      - name: Build Docker image
        run: |
          docker build -t deploy_application_in_cloudrun:${{ github.run_number }} .
          echo "${{ github.run_number }}" > versions.txt

          
  push_to_artifact_registry:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Authenticate with Artifact Registry
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

  deploy_to_cloudrun:
    runs-on: ubuntu-latest
    needs: push_to_artifact_registry
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run deploy Vinod \
      #       --image gcr.io/snappy-axle-412306/deploy_application_in_cloudrun:14 \
      #       --region us-central1 \
      #       --platform managed \
      #       --allow-unauthenticated \
      #       --project snappy-axle-412306
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy Vinod \
            --image gcr.io/snappy-axle-412306/deploy_application_in_cloudrun:14 \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project snappy-axle-412306
