name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    

      - name: Build Docker image
        run: |
          docker build -t deploy_application_in_cloudrun:${{ github.run_number }} .
          echo "${{ github.run_number }}" > versions.txt

          
  # push_to_artifact_registry:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Authenticate with Artifact Registry
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SA_KEY }}

  # deploy_to_cloudrun:
  #   runs-on: ubuntu-latest
  #   needs: push_to_artifact_registry
  #   steps:
  #     - name: Authenticate with Google Cloud
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SA_KEY }}

  #     - name: Deploy to Cloud Run
  #       run: |
  #         gcloud run deploy cloud-run-app \
  #           --image gcr.io/virtual-firefly-412705/docker:${{ github.run_number }} \
  #           --region us-central1 \
  #           --platform managed \
  #           --allow-unauthenticated
