name: Cloud Run Deployment

on:
  push:
    branches:
      - main  # Adjust this according to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/strange-firefly-384106/my-repository:v01 .
          docker push gcr.io/strange-firefly-384106/my-repository:v01  # Explicitly specify the tag

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy helloworld-app \
            --image gcr.io/strange-firefly-384106/my-repository:v01  # Specify the image tag
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet

        env:
          REGION: "us-central1"  # Replace "us-central1" with your desired region
