name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build . -t gcr.io/snappy-axle-412306/my-image:$GITHUB_RUN_NUMBER
        docker push gcr.io/snappy-axle-412306/my-image:$GITHUB_RUN_NUMBER

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@main
      with:
        image: us-central1-docker.pkg.dev/snappy-axle-412306/my-repo/my-image:$GITHUB_RUN_NUMBER
        service: my-image
        project_id: snappy-axle-412306
        region: us-central1
        platform: managed
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with Google Cloud
      run: gcloud auth configure-docker

    - name: Authenticate Docker with Google Cloud
      run: |
        gcloud auth configure-docker
        gcloud auth list
